### ISSUE TITLE
doesn't work on El Capitan

### ISSUE THREAD

**Issue by jiyzhang** [schreiberstein/lucidagrandeyosemite#19]
I tried to run the app on El Caption but it didn't work, ended with the error: 
-----------------------------------------------------------------------------------------------------------------
A different version of OS X system font Lucida Grande ('LucidaGrande.ttc') has been detected on your system.
The patch is not compatible with your system.
Please proceed and download the latest release version from :

https://github.com/schreiberstein/lucidagrandeyosemite

In case you're using an unreleased version of OS X, please report back!
-----------------------------------------------------------------------------------------------------------------

I checked the apple scripts included in the app and confirmed that the MD5 checksum value of the file 
"/System/Fonts/LucidaGrandte.ttc" had changed in El Capitan. I tried to copy the file from Yosemite to El Captian but failed due to the sanbox limitation. 

Will u develop a version for El Capitan?

**Comment by jiyzhang** [comment]
I checked the automator script included in the app, but I still didn't understand the way to change the system font.
1. Why the lucidagrande.ttc file shipped with Yosemite should be patched? 
    The same file shipped in El Capitan has changed as the MD5 checksum changed. Do we still need to patch it? 

2. As per the script, the file lucidagrande.ttc located in /System/Fonts was generated and a new file
        LucidaGrande_modsysfontyos.ttc
    was generated under /Library/Font, and after reboot the system font changed, but you didn't change any system configuration files. Could you please tell me the reason? 

3. If you want to upgrade this app to El Capitan, I really want to help

**Comment by vista980622** [comment]
I am the original author of the font patch (but not the app packaging). In short, I am looking at how it can be done, but don't expect anything soon.

While it appears on surface San Francisco has only 9 font weights, there are actually 33 for different display sizes and contexts. A correct mapping between LG font and SF font is required, and since we only have 2 variant of LG font now, the result will not be optimal.

The way El Capitan loads fonts have also changed. This, the typeface, combined with Apple's newly-introduced System Integrity Protection (a.k.a: rootless), there's a lot of work to do.

**Comment by jiyzhang** [comment]
Thanks very much for the information.  I'm not aware the system mechanism has changed in El Capitan. it seems lots of work ahead, I'll be waiting for the good news.

**Comment by gerardp** [comment]
Any news?
